/*
shottower
Copyright (C) 2022 Rémy Boulanouar

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/
/*
 * Shottower
 *
 * Shottower is the open source version of Shotstack which is a video, image and audio editing service that allows for the automated generation of videos, images and audio using JSON and a RESTful API.  You arrange and configure an edit and POST it to the API which will render your media and provide a file  location when complete.  For more details visit [shottower](https://github.com/DblK/shottower) or checkout our [getting started](https://shotstack.io/docs/guide/) documentation.  There are two main API's, one for editing and generating assets (Edit API) and one for managing hosted assets (Serve API).  The Edit API base URL is: <b>http://0.0.0.0:4000/{version}</b>  The Serve API base URL is: <b>http://0.0.0.0:4000/serve/{version}</b>
 *
 * API version: stage
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// Track - A track contains an array of clips. Tracks are layered on top of each other in the order in the array. The top most track will render on top of those below it.
type Track struct {

	// An array of Clips comprising of TitleClip, ImageClip or VideoClip.
	Clips []Clip `json:"clips"`
}

// AssertTrackRequired checks if the required fields are not zero-ed
func AssertTrackRequired(obj *Track) error {
	elements := map[string]interface{}{
		"clips": obj.Clips,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Schema: "Track", Field: name}
		}
	}

	for i := range obj.Clips {
		if err := AssertClipRequired(&obj.Clips[i]); err != nil {
			return err
		}
	}
	return nil
}

// AssertRecurseTrackRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of Track (e.g. [][]Track), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseTrackRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aTrack, ok := obj.(Track)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertTrackRequired(&aTrack)
	})
}
